export const Test1 = [
    {
        tag: 'lab',
        label: 'lab',
        isArray: false,
        isRequired: false,
        mbdbPath: 'lab',
        input: [
            {
                tag: 'name',
                label: 'name',
                isArray: false,
                isRequired: false,
                mbdbPath: 'lab/name',
                input: 'string',
                help: {
                    en: 'Name of the lab',
                },
            },
            {
                tag: 'description',
                label: 'description',
                isArray: false,
                isRequired: false,
                mbdbPath: 'lab/description',
                input: 'string',
                help: {
                    en: 'Description of the lab',
                },
            },
            {
                tag: 'instruments',
                label: 'instruments',
                isArray: true,
                isRequired: false,
                mbdbPath: 'lab/instruments[]',
                input: {
                    Centrifuge: {
                        tag: 'Centrifuge',
                        label: 'Centrifuge',
                        isArray: false,
                        isRequired: true,
                        mbdbPath: 'lab/instruments[]',
                        input: [
                            {
                                tag: 'max_rpm',
                                label: 'max_rpm',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/max_rpm',
                                input: 'float',
                                minimum: 0.0,
                                help: {
                                    en: 'The maximal rounds per minute the centrifuge can deliver',
                                },
                            },
                            {
                                tag: 'rotors',
                                label: 'rotors',
                                isArray: true,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/rotors[]',
                                input: 'string',
                                help: {
                                    en: 'List of rotors available to the centrifuge',
                                },
                            },
                            {
                                tag: 'id',
                                label: 'id',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/id',
                                input: 'referenceable-id',
                                referenceAs: 'instrument',
                            },
                            {
                                tag: 'name',
                                label: 'name',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/name',
                                input: 'string',
                                help: {
                                    en: 'The name of the instrument. Should be unique within a record',
                                },
                            },
                            {
                                tag: 'broken',
                                label: 'broken',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/broken',
                                input: 'boolean',
                                help: {
                                    en: 'Is the instrument broken (True=Broken, False=Working',
                                },
                            },
                            {
                                tag: 'type',
                                label: 'type',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/type',
                                input: 'variant-discriminator',
                                choices: [
                                    {
                                        tag: 'Centrifuge',
                                        title: 'Centrifuge',
                                    },
                                    {
                                        tag: 'Pipette',
                                        title: 'Pipette',
                                    },
                                ],
                                help: {
                                    en: 'The type of the instrument',
                                },
                            },
                        ],
                    },
                    Pipette: {
                        tag: 'Pipette',
                        label: 'Pipette',
                        isArray: false,
                        isRequired: true,
                        mbdbPath: 'lab/instruments[]',
                        input: [
                            {
                                tag: 'min_volume',
                                label: 'min_volume',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/min_volume',
                                input: 'float',
                                minimum: 0.0,
                                help: {
                                    en: 'The minimal volume',
                                },
                            },
                            {
                                tag: 'max_volume',
                                label: 'max_volume',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/max_volume',
                                input: 'float',
                                minimum: 0.0,
                                help: {
                                    en: 'The maximal volume',
                                },
                            },
                            {
                                tag: 'id',
                                label: 'id',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/id',
                                input: 'referenceable-id',
                                referenceAs: 'instrument',
                            },
                            {
                                tag: 'name',
                                label: 'name',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/name',
                                input: 'string',
                                help: {
                                    en: 'The name of the instrument. Should be unique within a record',
                                },
                            },
                            {
                                tag: 'broken',
                                label: 'broken',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/broken',
                                input: 'boolean',
                                help: {
                                    en: 'Is the instrument broken (True=Broken, False=Working',
                                },
                            },
                            {
                                tag: 'type',
                                label: 'type',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'lab/instruments[]/type',
                                input: 'variant-discriminator',
                                choices: [
                                    {
                                        tag: 'Centrifuge',
                                        title: 'Centrifuge',
                                    },
                                    {
                                        tag: 'Pipette',
                                        title: 'Pipette',
                                    },
                                ],
                                help: {
                                    en: 'The type of the instrument',
                                },
                            },
                        ],
                    },
                },
                discriminator: 'type',
                help: {
                    en: 'The list of instruments available to the lab',
                },
            },
        ],
    },
    {
        tag: 'scientists',
        label: 'scientists',
        isArray: true,
        isRequired: false,
        mbdbPath: 'lab/scientists[]',
        input: [
            {
                tag: 'id',
                label: 'id',
                isArray: false,
                isRequired: false,
                mbdbPath: 'lab/scientists[]/id',
                input: 'referenceable-id',
                referenceAs: 'scientist',
            },
            {
                tag: 'name',
                label: 'name',
                isArray: false,
                isRequired: false,
                mbdbPath: 'lab/scientists[]/name',
                input: 'string',
                help: {
                    en: 'Name of the scientist',
                },
            },
        ],
        help: {
            en: 'The list of scientist that work in the lab',
        },
    },
    {
        tag: 'daily_schedule',
        label: 'daily_schedule',
        isArray: false,
        isRequired: false,
        mbdbPath: 'daily_schedule',
        input: [
            {
                tag: 'date',
                label: 'date',
                isArray: false,
                isRequired: false,
                mbdbPath: 'daily_schedule/date',
                input: 'calendar-date',
                help: {
                    en: 'The date the schedule refer to in yyyy-mm-dd format',
                },
            },
            {
                tag: 'bookings',
                label: 'bookings',
                isArray: true,
                isRequired: false,
                mbdbPath: 'daily_schedule/bookings[]',
                input: [
                    {
                        tag: 'instrument',
                        label: 'instrument',
                        isArray: false,
                        isRequired: false,
                        mbdbPath: 'daily_schedule/bookings[]/instrument',
                        input: 'related-to',
                        relatesTo: 'instrument',
                        relatedKeys: [
                            'id',
                            'name',
                        ],
                    },
                    {
                        tag: 'time_slot',
                        label: 'time_slot',
                        isArray: false,
                        isRequired: true,
                        mbdbPath: 'daily_schedule/bookings[]/time_slot',
                        input: [
                            {
                                tag: 'begin',
                                label: 'begin',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'daily_schedule/bookings[]/time_slot/begin',
                                input: 'int',
                                minimum: 0,
                                maximum: 24,
                                help: {
                                    en: 'Starting time point of the booking',
                                },
                            },
                            {
                                tag: 'duration',
                                label: 'duration',
                                isArray: false,
                                isRequired: false,
                                mbdbPath: 'daily_schedule/bookings[]/time_slot/duration',
                                input: 'int',
                                minimum: 0,
                                maximum: 24,
                                help: {
                                    en: 'Duration of the booking in hours',
                                },
                            },
                        ],
                    },
                    {
                        tag: 'scientist',
                        label: 'scientist',
                        isArray: false,
                        isRequired: false,
                        mbdbPath: 'daily_schedule/bookings[]/scientist',
                        input: 'related-to',
                        relatesTo: 'scientist',
                        relatedKeys: [
                            'id',
                            'name',
                        ],
                    },
                ],
                help: {
                    en: 'List of bookings',
                },
            },
        ],
    },
];
